#index:
#    path: /
#    controller: App\Controller\PeopleController::homepage

hello_page:
  path: /sa
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction('hello_page.html.twig')
  defaults:
    templates: 'hello_page.html.twig'